# ================================================================
#   ██████╗ ██████╗ ████████╗██╗ ██████╗ ███╗   ██╗███████╗
#  ██╔═══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝
#  ██║   ██║██████╔╝   ██║   ██║██║   ██║██╔██╗ ██║███████╗
#  ██║   ██║██╔═══╝    ██║   ██║██║   ██║██║╚██╗██║╚════██║
#  ╚██████╔╝██║        ██║   ██║╚██████╔╝██║ ╚████║███████║
#   ╚═════╝ ╚═╝        ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝
# ================================================================
## Clearance levels: [Member: 0, Moderator: 1, Admin: 2, Owner:3]
#
Clans:

  # Max amount of clans the server can have
  max-clans: 60

  # Charge for clan creation? If so how much.
  creation:
    charge: false
    amount: 420.0

  # Allow clan bank balances to effect clan power (Requires 'Banks' addon).
  bank-influence: true

  # Allow clan member size and clan power to decide claim amounts.
  claim-influence:
    allow: false

  # Worlds allowed to use clans features.
  world-whitelist:
    - world
    - world_nether
    - world_the_end

  # Turn on or off the use of land claiming.
  land-claiming:
    allow: true
    # Change the minimum clearance level needed to claim land.
    clearance: 2
    # Change the minimum clearance level needed to un-claim all owned land.
    unclaim-all-clearance: 2
    # Turn on or off titles as players traverse land-scape.
    # Warning: REQUIRES a full server restart.
    send-titles: true
    # Set a cooldown for when players over-power a specified amount of land.
    over-powering:
      cooldown:
        # Use cooldown?
        enabled: true
        # How many minutes will the cooldown last?
        length: 5
        # After how many un-claims will the cooldown trigger?
        after-uses: 4

  # Change the minimum clearance required to change the clans name.
  rename-clearance: 3

  # Change the minimum clearance required to toggle clan friendly fire.
  friendlyfire-clearance: 3

  # Change the minimum clearance required to change the clans name COLOR.
  recolor-clearance: 1

  # Change the minimum clearance level needed to kick other clan members.
  kick-clearance: 2

  # Change the minimum clearance needed to promote/demote clan members.
  position-clearance: 2

  # Change the minimum clearance needed to change the clans password.
  password-clearance: 2

  # Change the minimum rank clearance needed to update the clan base.
  base-clearance: 1

  # Change the minimum rank clearance needed to use the clan stash (Requires 'Stash' addon).
  stash-clearance: 2

  # Change the minimum rank clearance needed to invite players to the clan.
  invite-clearance: 1

  # Change the minimum rank clearance needed to see the clan password
  password-visible-clearance: 3

  # Modify the raid-shield settings
  raid-shield:
    # Allow the raid-shield to run, enabling claim raiding?
    allow: true
    main-world: 'world'
    # Default: 0 for dawn
    up-time: 0
    # Default: 13000 for dusk
    down-time: 13000
    # Allow land over-powering while the shield is up.
    claiming: false
    # Clans will only be able to overclaim enemy clans with this option turned on.
    claiming-only-enemy: true
# =======================================================
#  ███████╗ ██████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗
#  ██╔════╝██╔═══██╗██╔══██╗████╗ ████║██╔══██╗╚══██╔══╝
#  █████╗  ██║   ██║██████╔╝██╔████╔██║███████║   ██║
#  ██╔══╝  ██║   ██║██╔══██╗██║╚██╔╝██║██╔══██║   ██║
#  ██║     ╚██████╔╝██║  ██║██║ ╚═╝ ██║██║  ██║   ██║
#  ╚═╝      ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝
# =======================================================
Formatting:
  # Let the plugin include chat formatting?
  allow: true
  # Allow clans to put prefixes before player names above heads.
  nametag-prefix: true
  # Change number formatting lang. [en = English, fr = French, de = german, nl = Dutch]
  # Warning: REQUIRES a full server restart.
  locale: en
  # Change the max size a clan tag can be.
  tag-size: 15
  # Allow the use of & symbol in clan tag's
  symbols: false
  # Change the prefix displayed for the plugin.
  Prefix: '&7[&6&lClans&7]'
  # Rank presentation style: [FULL, WORDLESS]
  Rank-Style: WORDLESS

  Styles:
    Full:
      # Note: Changing these styles will have an effect regardless of rank style.
      Member: 'Member'
      Moderator: 'Moderator'
      Admin: 'Admin'
      Owner: 'Owner'
    Wordless:
      Member: '•'
      Moderator: '••'
      Admin: '•••'
      Owner: '&4•❂•'

  # Change the formatting for global chat clan prefix
  # Two "%s" need placement in order for the formatting to work correctly
  ### The first one is the clan RANK and the second one is the clan NAME
  Chat: '&8(&b%s&8)&r &8[&3%s&8]&r'
# =====================================================================
#  ██████╗ ███████╗███████╗██████╗  ██████╗ ███╗   ██╗███████╗███████╗
#  ██╔══██╗██╔════╝██╔════╝██╔══██╗██╔═══██╗████╗  ██║██╔════╝██╔════╝
#  ██████╔╝█████╗  ███████╗██████╔╝██║   ██║██╔██╗ ██║███████╗█████╗
#  ██╔══██╗██╔══╝  ╚════██║██╔═══╝ ██║   ██║██║╚██╗██║╚════██║██╔══╝
#  ██║  ██║███████╗███████║██║     ╚██████╔╝██║ ╚████║███████║███████╗
#  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚══════╝
# =====================================================================
Response:
  creation: '&a&o%s created a &f%s &a&oclan &7%s'
  deletion: '&c&oClan "%s" has fallen...'
  kick-out: '&e&oPlayer "%s" was kicked from the clan.'
  kick-in: '&4&o%s kicked you from the clan.'
  password: '&b&o&nThe clan password has been changed.'
  promotion: '&a&oPlayer "%s" was promoted.'
  demotion: '&d&oPlayer "%s" was demoted.'
  tag: '&b&oThe clan name was changed to %s'
  base: '&aThe clan base location was updated.'
#-------------------------------------------------------------------
## -- DO NOT EDIT BELOW --
# Authors: Hempfest, Modify
# Contributors: Coolmike35
# Pro link: https://www.spigotmc.org/resources/clans-pro-modular-configurable-1-14-1-16.87515/
##------------------------
Version: 2.1.8