#
#----------------------------------,,-----------------------------
#    .g8""8q.               mm     db
#  .dP'    `YM.             MM
#  dM'      `MM `7MMpdMAo.mmMMmm `7MM  ,pW"Wq.`7MMpMMMb.  ,pP"Ybd
#  MM        MM   MM   `Wb  MM     MM 6W'   `Wb MM    MM  8I   `"
#  MM.      ,MP   MM    M8  MM     MM 8M     M8 MM    MM  `YMMMa.
#  `Mb.    ,dP'   MM   ,AP  MM     MM YA.   ,A9 MM    MM  L.   I8
#    `"bmmd"'     MMbmmd'   `Mbmo.JMML.`Ybmd9'.JMML  JMML.M9mmmP'
#                 MM
#---------------.JMML.---------------------------------------------
## Clearance levels: [Member: 0, Moderator: 1, Admin: 2, Owner:3]
#
Clans:

  # Change the max size a clan tag can be.
  tag-size: 15

  # Turn on or off the use of land claiming.
  land-claiming:
    allow: true
    # Change the minimum clearance level needed to claim land.
    clearance: 2
    # Change the minimum clearance level needed to un-claim all owned land.
    unclaim-all-clearance: 2
    # Turn on or off titles as players traverse land-scape.
    send-titles: true

  # Change the minimum clearance required to change the clans name.
  rename-clearance: 3

  # Change the minimum clearance required to change the clans name COLOR.
  recolor-clearance: 1

  # Change the minimum clearance level needed to kick other clan members.
  kick-clearance: 2

  # Change the minimum clearance needed to promote/demote clan members.
  position-clearance: 2

  # Change the minimum clearance needed to change the clans password.
  password-clearance: 2

  # Modify the raid-shield settings
  raid-shield:
    allow: true
    main-world: 'world'
    up-time: 0
    down-time: 13000
    # Decide whether to allow or deny the ability to overpower other clan claims
    ## while the shield is up.
    claiming: false

  # Change the minimum rank clearance needed to update the clan base.
  clan-base:
    clearance: 1
#-------------------------------------------------------------------
#
#----------------,,-----------------------
#    .g8"""bgd `7MM                 mm
#  .dP'     `M   MM                 MM
#  dM'       `   MMpMMMb.   ,6"Yb.mmMMmm
#  MM            MM    MM  8)   MM  MM
#  MM.           MM    MM   ,pm9MM  MM
#  `Mb.     ,'   MM    MM  8M   MM  MM
#    `"bmmmd'  .JMML  JMML.`Moo9^Yo.`Mbmo
#-----------------------------------------
#
#-------------------------------------------------------------------
Formatting:
  allow: true
  # Change the prefix displayed for the plugin.
  Prefix: '&7[&6&lClans&7]'
  # Rank presentation style: [FULL, WORDLESS]
  Rank-Style: WORDLESS
  
  Styles:
    Full:
      Member: 'Member'
      Moderator: 'Moderator'
      Admin: 'Admin'
      Owner: 'Owner'
    Wordless:
      Member: '❀'
      Moderator: '❃'
      Admin: '❁'
      Owner: '❂'

  # Change the formatting for global chat clan prefix
  # Two "%s" need placement in order for the formatting to work correctly
  ### The first one is the clan RANK and the second one is the clan NAME
  Chat: '&r(&e%s&r) [&6%s&r]'
#-------------------------------------------------------------------
#
# ----------------------------------------------------------------------------
#  `7MM"""Mq.
#    MM   `MM.
#    MM   ,M9  .gP"Ya  ,pP"Ybd `7MMpdMAo.  ,pW"Wq.`7MMpMMMb.  ,pP"Ybd  .gP"Ya
#    MMmmdM9  ,M'   Yb 8I   `"   MM   `Wb 6W'   `Wb MM    MM  8I   `" ,M'   Yb
#    MM  YM.  8M"""""" `YMMMa.   MM    M8 8M     M8 MM    MM  `YMMMa. 8M""""""
#    MM   `Mb.YM.    , L.   I8   MM   ,AP YA.   ,A9 MM    MM  L.   I8 YM.    ,
#  .JMML. .JMM.`Mbmmd' M9mmmP'   MMbmmd'   `Ybmd9'.JMML  JMML.M9mmmP'  `Mbmmd'
#                                MM
# -----------------------------.JMML.------------------------------------------
#
#-------------------------------------------------------------------
Response:
  creation: '&a&o%s created an &f%s &a&oclan &7%s'
  deletion: '&c&oClan "%s" has fallen...'
  kick-out: '&e&oPlayer "%s" was kicked from the clan.'
  kick-in: '&4&o%s kicked you from the clan.'
  password: '&b&o&nThe clan password has been changed.'
  promotion: '&a&oPlayer "%s" was promoted.'
  demotion: '&d&oPlayer "%s" was demoted.'
  tag: '&b&oThe clan name was changed to %s'
  base: '&aThe clan base location was updated.'
#-------------------------------------------------------------------
## -- DO NOT EDIT BELOW --
# Authors: Hempfest, Modify
# Contributors: Coolmike35
# Pro link: ??
##------------------------
Version: 2.0.7