name: Clans
version: 2.2.0
author: Hempfest
api-version: 1.13
depend: [ Labyrinth ]
soft-depend: [ PlaceholderAPI ]
description: A simple player grouping plugin with alliance / enemy implementations.
main: com.youtube.hempfest.clans.HempfestClans